# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1750a7155c500872038768ab078487797934e1768ae2acdd9828ba6bcc6ba5730bcdcc3e044cfafb08170724019410e4fc17275eb203834613ac56e258dcfcfa

test:
  secret_key_base: 6ea095dc4a7814496fd22291361a228d3511c34c6c0d13ac7e7cd2f14b09bf105b5e9490a79900978dbcd255b540fac2fd186d363eb9d42406f2696388261395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
